### ISSUE TITLE
Changing color does not work

### ISSUE THREAD

**Issue by mczero80** [unbibium/atari64#1]
Hello, great work!

I have found a bug:
Changing colors does not work.

Like:
`PRINT "{RED}Hello World`
does not change the cursor color.

Also, poking 646,X does not change the color, but I expected that.

**Comment by unbibium** [comment]
The Atari's ANTIC/GTIA chips can't do color in 40-column text mode, so color text will never work on stock hardware.  Indeed, the whole $D800-$DFFF space has been claimed for the PETSCII font, and most color code had to be removed to keep it from being modified.

However, take heart, for the PETSCII color codes do in fact change `PEEK(646)`, so at least there's that.
